// Generated by js_of_ocaml 3.1.0
(function(d){"use strict";var
aA=" : flags Open_text and Open_binary are not compatible",al="Sys_error",az=224,ay="Invalid_argument",ax='"',t=1024,K="jsError",aw="input",aj=785140586,ak=57343,av=512,ai=982028505,au="End_of_file",at="Failure",ag="Undefined_recursive_module",ah=" : flags Open_rdonly and Open_wronly are not compatible",af="([^/]*)",as="Stack_overflow",g=128,b="",J="^",ab=" : file already exists",ac=2048,ad=56320,ae=240,f=248,ar="Not_found",aa="Assert_failure",n="/",ap="Sys_blocked_io",aq="fd ",$="Out_of_memory",ao="Match_failure",am="Division_by_zero",an="static/";function
bs(c,e){var
d=c.length,b=new
Array(d+1),a=0;for(;a<d;a++)b[a]=c[a];b[a]=e;return b}function
P(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
C(b,a){if(b.fun)return C(b.fun,a);var
c=b.length,d=a.length,e=c-d;if(e==0)return b.apply(null,a);else
if(e<0)return C(b.apply(null,P(a,0,c)),P(a,c,d-c));else
return function(c){return C(b,bs(a,c))}}var
bc=0;function
v(){return bc++}var
D={amp:/&/g,lt:/</g,quot:/\"/g,all:/[&<\"]/};function
aG(a){if(!D.all.test(a))return a;return a.replace(D.amp,"&amp;").replace(D.lt,"&lt;").replace(D.quot,"&quot;")}function
aF(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
bo(f){for(var
h=b,c=h,a,j,d=0,i=f.length;d<i;d++){a=f.charCodeAt(d);if(a<g){for(var
e=d+1;e<i&&(a=f.charCodeAt(e))<g;e++);if(e-d>av){c.substr(0,1);h+=c;c=b;h+=f.slice(d,e)}else
c+=f.slice(d,e);if(e==i)break;d=e}if(a<ac){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(g|a&63)}else
if(a<55296||a>=ak)c+=String.fromCharCode(az|a>>12,g|a>>6&63,g|a&63);else
if(a>=56319||d+1==i||(j=f.charCodeAt(d+1))<ad||j>ak)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;c+=String.fromCharCode(ae|a>>18,g|a>>12&63,g|a>>6&63,g|a&63)}if(c.length>t){c.substr(0,1);h+=c;c=b}}return h+c}function
bg(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
O(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=t,a-=t)f+=e.apply(null,P(c,d,Math.min(a,t)));return f}function
aD(a){if(a.t==2)a.c+=bg(a.l-a.c.length,"\0");else
a.c=O(a.c,0,a.c.length);a.t=0}function
bn(f){for(var
l=b,d=b,i,h,j,a,c=0,k=f.length;c<k;c++){h=f.charCodeAt(c);if(h<g){for(var
e=c+1;e<k&&(h=f.charCodeAt(e))<g;e++);if(e-c>av){d.substr(0,1);l+=d;d=b;l+=f.slice(c,e)}else
d+=f.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((j=f.charCodeAt(c))&-64)==g){i=j+(h<<6);if(h<az){a=i-12416;if(a<g)a=1}else{a=2;if(++c<k&&((j=f.charCodeAt(c))&-64)==g){i=j+(i<<6);if(h<ae){a=i-925824;if(a<ac||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=f.charCodeAt(c))&-64)==g&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),ad+(a&1023));else
d+=String.fromCharCode(a);if(d.length>t){d.substr(0,1);l+=d;d=b}}return l+d}function
bm(a){switch(a.t){case
9:return a.c;default:aD(a);case
0:if(aF(a.c)){a.t=9;return a.c}a.t=8;case
8:return bn(a.c)}}function
o(c,a,b){this.t=c;this.c=a;this.l=b}o.prototype.toString=function(){return bm(this)};function
N(a){var
b=9;if(!aF(a))b=8,a=bo(a);return new
o(b,a,a.length)}function
be(b,a){throw[0,b,a]}function
a(a){return new
o(0,a,a.length)}function
aL(c,b){be(c,a(b))}var
c=[0];function
j(a){aL(c.Sys_error,a)}var
p=new
Array();function
a_(e){var
a=p[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&c.fds[a.fd]&&c.fds[a.fd].output){var
d=c.fds[a.fd].output;switch(d.length){case
2:d(e,a.buffer);break;default:d(a.buffer)}}a.buffer=b;return 0}if(d.process&&d.process.cwd)var
u=d.process.cwd().replace(/\\/g,n);else
var
u="/static";if(u.slice(-1)!==n)u+=n;function
a9(a){a=a
instanceof
o?a.toString():a;if(a.charCodeAt(0)!=47)a=u+a;var
e=a.split(n),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
bd(a){a=a
instanceof
o?a.toString():a;j(a+": No such file or directory")}function
bi(a){return new
o(4,a,a.length)}function
aE(a){aL(c.Invalid_argument,a)}function
aO(){aE("index out of bounds")}function
bk(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
bh(b,a){if(a>>>0>=b.l)aO();return bk(b,a)}function
r(a){if(a<0)aE("String.create");return new
o(a?2:9,b,a)}function
aI(a){return a.l}function
M(b){if(d.Uint8Array)var
c=new(d.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
f=b.c,e=f.length,a=0;for(;a<e;a++)c[a]=f.charCodeAt(a);for(e=b.l;a<e;a++)c[a]=0;b.c=c;b.t=4;return c}function
B(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?O(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?O(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)M(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aB(){}function
e(a){this.data=a}e.prototype=new
aB();e.prototype.truncate=function(a){var
b=this.data;this.data=r(a|0);B(b,0,this.data,0,a)};e.prototype.length=function(){return aI(this.data)};e.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=r(b+a),f=this.data;this.data=e;B(f,0,this.data,0,c)}B(d,g,this.data,b,a);return 0};e.prototype.read=function(c,a,d,b){var
e=this.length();B(this.data,c,a,d,b);return 0};e.prototype.read_one=function(a){return bh(this.data,a)};e.prototype.close=function(){};e.prototype.constructor=e;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!=0)this.content[b]=new
e(c[1])}};h.prototype.exists=function(a){if(a==b)return 1;var
d=a+n,e=new
RegExp(J+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==b?b:d+n,h=new
RegExp(J+g+af),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};h.prototype.is_dir=function(a){var
e=a==b?b:a+n,f=new
RegExp(J+e+af),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+ah);if(b.text&&b.binary)j(this.nm(a)+aA);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+ab);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
e(r(0));return this.content[a]}else
bd(this.nm(a))};h.prototype.register=function(c,b){if(this.content[c])j(this.nm(c)+ab);if(b
instanceof
o)this.content[c]=new
e(b);else
if(b
instanceof
Array)this.content[c]=new
e(bi(b));else
if(b.toString){var
d=a(b.toString());this.content[c]=new
e(d)}};h.prototype.constructor=h;function
aC(a){if(a.t!=4)M(a);return a.c}function
bl(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}M(a)}a.c[c]=b;return 0}function
bj(b,a,c){if(a>>>0>=b.l)aO();return bl(b,a,c)}var
L=d.Buffer;function
l(a){this.fs=require("fs");this.fd=a}l.prototype=new
aB();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,b,c,f){var
a=aC(b);if(!(a
instanceof
d.Uint8Array))a=new(d.Uint8Array)(a);var
e=new
L(a);this.fs.writeSync(this.fd,e,c,f,g);return 0};l.prototype.read=function(h,e,c,g){var
a=aC(e);if(!(a
instanceof
d.Uint8Array))a=new(d.Uint8Array)(a);var
f=new
L(a);this.fs.readSync(this.fd,f,c,g,h);for(var
b=0;b<g;b++)bj(e,c+b,f[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(d.Uint8Array)(1),a=new
L(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require("fs");this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
s=u.match(/[^\/]*\//)[0],w=[];if(typeof
module!=="undefined"&&module.exports&&typeof
require!=="undefined")w.push({path:s,device:new
k(s)});else
w.push({path:s,device:new
h(s)});w.push({path:s+an,device:new
h(s+an)});function
bt(b){var
f=a9(b),b=f.join(n),e=b+n,c;for(var
d=0;d<w.length;d++){var
a=w[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
aN(e,f){var
b=p[e],d=a(f),c=aI(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
bq(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
br(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
E(d,f,e,a){if(c.fds===undefined)c.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;c.fds[d]=b;if(!c.fd_last_idx||d>c.fd_last_idx)c.fd_last_idx=d;return d}function
bu(d,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(d.toString()+ah);if(a.text&&a.binary)j(d.toString()+aA);var
e=bt(d),f=e.device.open(e.rest,a),g=c.fd_last_idx?c.fd_last_idx:0;return E(g+1,aN,f,a)}E(0,aN,new
e(r(0)));E(1,br,new
e(r(0)));E(2,bq,new
e(r(0)));function
a$(d){var
b=c.fds[d];if(b.flags.wronly)j(aq+d+" is writeonly");var
a={file:b.file,offset:b.offset,fd:d,opened:true,out:false,refill:null};p[a.fd]=a;return a.fd}function
aH(e){var
d=c.fds[e];if(d.flags.rdonly)j(aq+e+" is readonly");var
a={file:d.file,offset:d.offset,fd:e,opened:true,out:true,buffer:b};p[a.fd]=a;return a.fd}function
ba(){var
b=0;for(var
a=0;a<p.length;a++)if(p[a]&&p[a].opened&&p[a].out)b=[0,p[a].fd,b];return b}function
bb(a){return a
instanceof
Array?a[0]:a
instanceof
o?252:1e3}function
i(d,b,a){c[d+1]=b;if(a)c[a]=b}var
aK={};function
a8(a){if((a.t&6)!=0)aD(a);return a.c}function
bf(a,b){aK[a8(a)]=b;return 0}function
aM(a){return a}function
aJ(a){return aK[a]}function
bp(a){if(a
instanceof
Array)return a;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))return aM(c.Stack_overflow);if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))return aM(c.Stack_overflow);if(a
instanceof
d.Error&&aJ(K))return[0,aJ(K),a];return[0,c.Failure,N(String(a))]}function
A(a,b){return a.length==1?a(b):C(a,[b])}var
Q=[f,a(al),-2];i(11,[f,a(ag),-12],ag);i(10,[f,a(aa),-11],aa);i(9,[f,a(ap),-10],ap);i(8,[f,a(as),-9],as);i(7,[f,a(ao),-8],ao);i(6,[f,a(ar),-7],ar);i(5,[f,a(am),-6],am);i(4,[f,a(au),-5],au);i(3,[f,a(ay),-4],ay);i(2,[f,a(at),-3],at);i(1,Q,al);i(0,[f,a($),-1],$);v(0);a$(0);aH(1);aH(2);v(0);v(0);var
R=[0,0],aV=a("Js.Error"),a2=a("canvas"),aZ=a("br"),aY=a("div"),aX=a(aw),a0=a("Dom_html.Canvas_not_available"),a4=a("Resume"),a5=a("Pause"),a6=a("Fixed position"),a7=a("Follow rotation");function
S(a){R[1]=[0,a,R[1]];return 0}var
x=d,aR=null,aS=undefined;function
T(a){return 1-(a==aR?1:0)}var
U=x.Array,V=[f,aV,v(0)],F=[0,V,{}],aT=true,aU=false,aQ=bb(F)===f?F:F[1];bf(a(K),aQ);(function(a){throw a});S(function(a){return a[1]===V?[0,N(a[2].toString())]:0});S(function(a){return a
instanceof
U?0:[0,N(a.toString())]});function
q(b,a){b.appendChild(a);return 0}function
W(c){return function(a){if(T(a)){var
d=A(c,a);if(1-(d|0))a.preventDefault();return d}var
e=event,b=A(c,e);if(1-(b|0))e.returnValue=b;return b}}var
X="2d",m=x.document;function
y(a,b){return a?A(b,a[1]):0}function
G(b,a){return b.createElement(a.toString())}function
H(b,a){return G(b,a)}var
Y=[0,aj];function
aW(f,e,d,c){for(;;){if(0===f)if(0===e)return G(d,c);var
h=Y[1];if(aj===h){try{var
j=m.createElement('<input name="x">'),k=j.tagName.toLowerCase()===aw?1:0,n=k?j.name==="x"?1:0:k,i=n}catch(a){var
i=0}var
l=i?ai:-1003883683;Y[1]=l;continue}if(ai<=h){var
a=new
U();a.push("<",c.toString());y(f,function(b){a.push(' type="',aG(b),ax);return 0});y(e,function(b){a.push(' name="',aG(b),ax);return 0});a.push(">");return d.createElement(a.join(b))}var
g=G(d,c);y(f,function(a){return g.type=a});y(e,function(a){return g.name=a});return g}}function
I(a){return H(a,aY)}var
a1=[f,a0,v(0)];x.HTMLElement===aS;var
z=600,a3="button";function
Z(f,e,d){var
b=[0,0],c=f.toString(),g=e.toString(),a=aW([0,a3],0,m,aX);a.value=c;a.onclick=W(function(f){b[1]=1-b[1];var
e=b[1]?g:c;a.value=e;A(d,b[1]);return aT});return a}function
_(c,b){var
a=H(m,a2);if(1-T(a.getContext))throw a1;a.width=c;a.height=b;return a}x.onload=W(function(h){var
c=_(z,z),e=_(z,z);q(m.body,c);c.getContext(X);e.getContext(X);var
b=I(m);b.className="controls";var
d=I(m);q(d,m.createTextNode("Click and drag mouse to rotate."));q(b,d);var
a=I(m),f=[0,0],g=[0,0];q(a,Z(a5,a4,function(a){f[1]=a;return 0}));q(a,H(m,aZ));q(a,Z(a7,a6,function(a){g[1]=a;return 0}));q(b,a);return aU});function
aP(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{a_(d)}catch(a){a=bp(a);if(a[1]!==Q)throw a}var
a=c;continue}return 0}}aP(ba(0));return}(function(){return this}()));
